openapi: 3.0.0
info:
  title: Circulation item API
  version: v1
paths:
  /circulation-item/{circulationItemId}:
    post:
      description: Add new circulation item
      operationId: createCirculationItem
      requestBody:
        $ref: "#/components/requestBodies/CirculationItemBody"
      responses:
        '201':
          description: Circulation Item created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItem"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "schemas/common.yaml#/Error"
        '422':
          $ref: "#/components/responses/trait_validate_422"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "schemas/common.yaml#/Error"
    get:
      description: Retrieve circulation item
      operationId: retrieveCirculationItemById
      responses:
        '200':
          description: Circulation Item retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItem"
        '404':
          description: Circulation Item not found
          content:
            application/json:
              schema:
                $ref: "schemas/common.yaml#/Error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "schemas/common.yaml#/Error"
    put:
      responses:
        '200':
          description: Circulation Item updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/circulationItem"
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
                example: Bad request
        '404':
          description: Circulation Item not found
          content:
            text/plain:
              schema:
                type: string
                example: Circulation Item not found
        '500':
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
      description: Change the circulation item
      operationId: updateCirculationItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/circulationItem"
        required: true
    parameters:
      - name: circulationItemId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/uuid"

components:
  responses:
    trait_validate_422:
      description: Validation errors
      content:
        application/json:
          example: examples/errors.sample
          schema:
            $ref: "#/components/schemas/errors"
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
    '500':
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errors"
  schemas:
    circulationItem:
      $ref: schemas/circulationItem.json
    circulationItems:
      allOf:
        - $ref: schemas/baseCollection.json
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/circulationItem"
          required:
            - items
    errors:
      $ref: schemas/errors.json
    uuid:
      $ref: schemas/uuid.json
  parameters:
    trait_queryable_query:
      name: query
      in: query
      description: A query string to filter rules based on matching criteria in fields.
      schema:
        type: string
    trait_pageable_offset:
      name: offset
      in: query
      description: Skip over a number of elements by specifying an offset value for the query
      schema:
        default: 0
        minimum: 0
        maximum: 2147483647
        type: integer
    trait_pageable_limit:
      name: limit
      in: query
      description: Limit the number of elements returned in the response
      schema:
        default: 10
        minimum: 0
        maximum: 2147483647
        type: integer
  requestBodies:
    CirculationItemBody:
          description: Circulation Item object
          required: true
          content:
            application/json:
              schema:
                $ref: "schemas/item.yaml#/CirculationItem"

